---
- name: Testing the BD loop
  ansible.builtin.debug:
    msg: "{{ bd_loop.name }}"
- name: Bridge Domain
  cisco.aci.aci_bd:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    state: "present"
    validate_certs: False
    tenant: "{{ tenant_loop.name }}"
    vrf: "{{ vrf_loop.name }}"
    bd: "{{ bd_loop.name }}"
- name: Run subnet loop
  ansible.builtin.include_tasks: ../tasks/L4_subnet_loop.yml
  loop: "{{ bd_loop.subnets }}"
  loop_control:
    loop_var: subnet_loop
  ignore_errors: true # Some BDs might not have subnets